version: '3.8'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx-domain.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt/live/api1.abdullah-javed.com/fullchain.pem:/etc/letsencrypt/live/api1.abdullah-javed.com/fullchain.pem:ro
      - /etc/letsencrypt/live/api1.abdullah-javed.com/privkey.pem:/etc/letsencrypt/live/api1.abdullah-javed.com/privkey.pem:ro
      - /etc/letsencrypt/live/api2.abdullah-javed.com-0001/fullchain.pem:/etc/letsencrypt/live/api2.abdullah-javed.com-0001/fullchain.pem:ro
      - /etc/letsencrypt/live/api2.abdullah-javed.com-0001/privkey.pem:/etc/letsencrypt/live/api2.abdullah-javed.com-0001/privkey.pem:ro
      - /etc/letsencrypt/live/abdullah-javed.com/fullchain.pem:/etc/letsencrypt/live/abdullah-javed.com/fullchain.pem:ro
      - /etc/letsencrypt/live/abdullah-javed.com/privkey.pem:/etc/letsencrypt/live/abdullah-javed.com/privkey.pem:ro
    depends_on:
      - set-cookie-service
      - secure-endpoint-service

  set-cookie-service:
    build: ./set-cookie-service
    ports:
      - "4001:4001"

  secure-endpoint-service:
    build: ./secure-endpoint-service
    ports:
      - "4002:4002"
  frontend-service:
    build: ./frontend
    ports:
      - "4000:4000"
