server {
    listen 80;
    server_name localhost;

    # Proxy API requests to Node backend
    location /api/ {
        proxy_pass http://3.108.119.62:4000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }

    # Proxy everything else to React frontend
    location / {
        proxy_pass http://3.108.119.62:5500/public/index.html;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }
}