events {}

http {
    # Redirect HTTP traffic to HTTPS for api1 and api2
    server {
        listen 80;
        server_name api1.abdullah-javed.com api2.abdullah-javed.com abdullah-javed.com;

        location / {
            return 301 https://$host$request_uri;
        }
    }

    # SSL configuration for api1
    server {
        listen 443 ssl;
        server_name api1.abdullah-javed.com;

        ssl_certificate /etc/letsencrypt/live/api1.abdullah-javed.com/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/api1.abdullah-javed.com/privkey.pem;

        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_ciphers 'ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES128-GCM-SHA256';
        ssl_prefer_server_ciphers on;

        location / {
            proxy_pass http://set-cookie-service:4001;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }

    # SSL configuration for api2
    server {
        listen 443 ssl;
        server_name api2.abdullah-javed.com;

        ssl_certificate /etc/letsencrypt/live/api2.abdullah-javed.com-0001/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/api2.abdullah-javed.com-0001/privkey.pem;

        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_ciphers 'ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES128-GCM-SHA256';
        ssl_prefer_server_ciphers on;

        location / {
            proxy_pass http://secure-endpoint-service:4002;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }

    # SSL configuration for frontend
    server {
        listen 443 ssl;
        server_name abdullah-javed.com;

        ssl_certificate /etc/letsencrypt/live/abdullah-javed.com/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/abdullah-javed.com/privkey.pem;

        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_ciphers 'ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES128-GCM-SHA256';
        ssl_prefer_server_ciphers on;

        location / {
            proxy_pass http://frontend-service:4000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}
