events {}

http {
  server {
    listen 80;

    location /set-cookie {
      proxy_pass http://set-cookie-service:4001;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }

    location /secure-endpoint {
      proxy_pass http://secure-endpoint-service:4002;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }
  }
}
